Repository arduino/ArduinoCore-renesas, pull requests merged in 2023-12, with the labels that each got.

#176 WiFiC3 - dnsIP(n) getter added
  libraries/WiFi/src/WiFi.cpp
  libraries/WiFi/src/WiFiC3.h
Labels: type: enhancement, topic: code

#198 Add gallery of icons and animations
  libraries/Arduino_LED_Matrix/examples/DisplaySingleFrame/DisplaySingleFrame.ino
  libraries/Arduino_LED_Matrix/library.properties
  libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h
  libraries/Arduino_LED_Matrix/src/gallery.h
Labels: type: enhancement, topic: code

#203 Fix: Increase accuracy of "delay()" routine.
  cores/arduino/time.cpp
Labels: type: imperfection, topic: code

#204 Provide frequency/duty_cycle API for PwmOut::begin(...).
  cores/arduino/pwm.cpp
  cores/arduino/pwm.h
Labels: type: enhancement, topic: code

#140 WiFiS3 WiFiServer operator bool
  libraries/WiFiS3/src/WiFiServer.cpp
  libraries/WiFiS3/src/WiFiServer.h
Labels: type: enhancement, topic: code

#133 WiFiS3 example WiFiPagerServer
  libraries/WiFiS3/examples/WiFiPagerServer/WiFiPagerServer.ino
  libraries/WiFiS3/examples/WiFiPagerServer/arduino_secrets.h
Labels: topic: documentation, type: enhancement

#185 WiFiC3 example WiFiPagerServer
  libraries/WiFi/examples/WiFiPagerServer/WiFiPagerServer.ino
  libraries/WiFi/examples/WiFiPagerServer/arduino_secrets.h
Labels: topic: documentation, type: enhancement

#175 WiFiS3/C3 - add legacy wl_enc_type constants aliases
  libraries/WiFiS3/src/WiFiTypes.h
  libraries/lwIpWrapper/src/CNetIf.h
Labels: type: enhancement, topic: code

#205 Fix: compilation of "ESP32_Test.ino" fails due to non-existent function "begin".
  libraries/ESPhost/examples/ESP32_TEST/ESP32_TEST.ino
Labels: type: imperfection, topic: documentation

#184 WiFiC3 - macAddress() return normal bytes ordering
  libraries/WiFi/examples/ConnectWithWPA/ConnectWithWPA.ino
  libraries/WiFi/examples/ScanNetworks/ScanNetworks.ino
  libraries/WiFi/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
  libraries/WiFi/src/WiFi.cpp
Labels: type: enhancement, topic: code

#183 WiFiS3 - macAddress() return normal bytes ordering
  libraries/WiFiS3/examples/ConnectWithWPA/ConnectWithWPA.ino
  libraries/WiFiS3/examples/ScanNetworks/ScanNetworks.ino
  libraries/WiFiS3/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
  libraries/WiFiS3/src/WiFi.cpp
  libraries/WiFiS3/src/WiFi.h
Labels: type: enhancement, topic: code
