Repository arduino/ArduinoCore-renesas, pull requests merged in 2023-10, with the labels that each got.

#137 Portenta C33: Msd QSPI examples, mount both partition
  libraries/UsbMsd/examples/MSD_QSPI/MSD_QSPI.ino
Labels: topic: documentation

#142 Add a USB mass storage disconnected callback
  libraries/UsbHostMsd/UsbHostMsd.cpp
  libraries/UsbHostMsd/UsbHostMsd.h
  libraries/UsbHostMsd/tu_msc.c
Labels: type: enhancement, topic: code

#157 SFU add download function and OTA example
  libraries/SFU/examples/OTAUpdate/OTAUpdate.ino
  libraries/SFU/examples/OTAUpdate/arduino_secrets.h
  libraries/SFU/src/SFU.cpp
  libraries/SFU/src/SFU.h
Labels: type: enhancement, topic: code

#159 mbedtls: enable server name indication extension
  extras/tls/config-c33.h
  libraries/SSLClient/src/cortex-m33/libmbedcrypto.a
  libraries/SSLClient/src/cortex-m33/libmbedtls.a
  libraries/SSLClient/src/cortex-m33/libmbedx509.a
Labels: type: enhancement, topic: code

#151 [WIRE-98] Ethernet driver and LWIP wrapper fixes
  extras/net/lwipopts.h
  libraries/Ethernet/src/EthernetDriver.cpp
  libraries/Ethernet/src/EthernetDriver.h
  libraries/lwIpWrapper/src/CNetIf.cpp
  libraries/lwIpWrapper/src/CNetIf.h
  libraries/lwIpWrapper/src/cortex-m33/liblwIP.a
Labels: type: imperfection, topic: code
