Repository arduino/ArduinoCore-renesas, pull requests merged in 2023-08, with the labels that each got.

#89 Fix undefined behavior in RTC.begin()
  libraries/RTC/src/RTC.cpp
Labels: type: imperfection, topic: code

#86 analogReference: fix heap corruption
  cores/arduino/analog.cpp
Labels: type: imperfection, topic: code

#52 Bugfix: `micros()` returns smaller number when timer wraps
  .gitignore
  cores/arduino/time.cpp
Labels: type: enhancement, topic: code

#87 platform: properly define _XOPEN_SOURCE
  platform.txt
Labels: type: imperfection, topic: code

#46 Wire: fix setClock
  libraries/Wire/Wire.cpp
  libraries/Wire/Wire.h
Labels: type: imperfection, topic: code

#101 [MKC-1088] Add comments
  libraries/AnalogWave/examples/DACEqualTemperedScale/DACEqualTemperedScale.ino
  libraries/AnalogWave/examples/DACJacques/DACJacques.ino
  libraries/AnalogWave/examples/SineWave/SineWave.ino
  libraries/Arduino_CAN/examples/CANRead/CANRead.ino
  libraries/Arduino_CAN/examples/CANWrite/CANWrite.ino
  libraries/Arduino_FreeRTOS/examples/FreeRTOS-Blink/FreeRTOS-Blink.ino
  libraries/Arduino_LED_Matrix/examples/DisplaySingleFrame/DisplaySingleFrame.ino
  libraries/Arduino_LED_Matrix/examples/GameOfLife/GameOfLife.ino
  libraries/Arduino_LED_Matrix/examples/LivePreview/LivePreview.ino
  libraries/Arduino_LED_Matrix/examples/MatrixFrameBuffer/MatrixFrameBuffer.ino
  libraries/Arduino_LED_Matrix/examples/MatrixIntro/MatrixIntro.ino
  libraries/Arduino_LED_Matrix/examples/PlayAnimation/PlayAnimation.ino
  libraries/EEPROM/examples/eeprom_read/eeprom_read.ino
  libraries/EEPROM/examples/eeprom_write/eeprom_write.ino
  libraries/RTC/examples/RTC_Alarm/RTC_Alarm.ino
  libraries/RTC/examples/RTC_AutomaticExample/RTC_AutomaticExample.ino
  libraries/RTC/examples/RTC_NTPSync/RTC_NTPSync.ino
  libraries/RTC/examples/RTC_PeriodicExample/RTC_PeriodicExample.ino
  libraries/RTC/examples/Test_RTC/Test_RTC.ino
  libraries/WiFiS3/examples/AP_SimpleWebServer/AP_SimpleWebServer.ino
  libraries/WiFiS3/examples/ConnectWithWPA/ConnectWithWPA.ino
  libraries/WiFiS3/examples/ScanNetworks/ScanNetworks.ino
  libraries/WiFiS3/examples/ScanNetworksAdvanced/ScanNetworksAdvanced.ino
  libraries/WiFiS3/examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino
  libraries/WiFiS3/examples/WiFiChatServer/WiFiChatServer.ino
  libraries/WiFiS3/examples/WiFiUdpNtpClient/WiFiUdpNtpClient.ino
  libraries/WiFiS3/examples/WiFiUdpSendReceiveString/WiFiUdpSendReceiveString.ino
  libraries/WiFiS3/examples/WiFiWebClient/WiFiWebClient.ino
  libraries/WiFiS3/examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino
  libraries/WiFiS3/examples/WiFiWebClientSSL/WiFiWebClientSSL.ino
  libraries/WiFiS3/examples/WiFiWebServer/WiFiWebServer.ino
Labels: topic: documentation, type: enhancement
