Repository arduino/ArduinoCore-renesas, pull requests merged in 2024-05, with the labels that each got.

#300 [Arduino_CAN] fix regression introduced in #296.
  libraries/Arduino_CAN/src/R7FA6M5_CAN.cpp
  libraries/Arduino_CAN/src/R7FA6M5_CAN.h
Labels: type: imperfection, topic: code

#280 Add a clear() method to the LED matrix library
  libraries/Arduino_LED_Matrix/examples/DisplaySingleFrame/DisplaySingleFrame.ino
  libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h
Labels: type: enhancement, topic: code

#317 Fix buffer-overflow assigning global Wire instances.
  libraries/Wire/Wire.cpp
  libraries/Wire/Wire.h
Labels: type: imperfection, topic: code

#316 Adding Generic Interrupt function to IRQManager
  cores/arduino/IRQManager.cpp
  cores/arduino/IRQManager.h
Labels: type: enhancement, topic: code

#318 libraries: Fix possible buffer/stack overflows in multiple libraries.
  libraries/SE05X/src/lib/platform/arduino/sm_port.cpp
  libraries/SSLClient/src/ssl_debug.cpp
  libraries/WiFiS3/src/Modem.cpp
  libraries/lwIpWrapper/src/CNetIf.cpp
Labels: type: imperfection, topic: code

#319 Fix for I2C bus not always working correctly after a slave device call end()
  libraries/Wire/Wire.cpp
Labels: type: imperfection, topic: code

#323 Add compiler.xxx.extra_flags to receipes in platform.txt
  platform.txt
Labels: type: enhancement, topic: code

#322 Fix Inconsistent Sleep Current by relocating the Ethernet Clock AGT Timer
  libraries/Ethernet/src/Ethernet.cpp
  libraries/Ethernet/src/EthernetC33.h
  libraries/Ethernet/src/EthernetClock.cpp
  libraries/Ethernet/src/EthernetClock.h
  variants/PORTENTA_C33/pins_arduino.h
  variants/PORTENTA_C33/variant.cpp
Labels: type: imperfection, topic: code

#285 WiFiS3 Modem: change write and write_nowait format argument to const char *
  libraries/WiFiS3/src/Modem.cpp
  libraries/WiFiS3/src/Modem.h
Labels: type: enhancement, topic: code

#278 WiFiS3: WiFiWebClientSSL fix information about CA Root certificate
  libraries/WiFiS3/examples/WiFiWebClientSSL/WiFiWebClientSSL.ino
Labels: type: imperfection, topic: documentation

#284 WiFiS3 Udp, Client: avoid RX_BUFFER_DIM redefinition
  libraries/WiFiS3/src/WiFiClient.h
  libraries/WiFiS3/src/WiFiUdp.h
Labels: type: imperfection, topic: code

#320 bounds check for last_interrupt_index
  cores/arduino/IRQManager.cpp
  cores/arduino/IRQManager.h
Labels: type: enhancement, topic: code

#324 Add RTC alarm setter without callback
  libraries/RTC/src/RTC.cpp
  libraries/RTC/src/RTC.h
Labels: type: enhancement, topic: code

#306 Add I2S support.
  cores/arduino/IRQManager.cpp
  cores/arduino/IRQManager.h
  libraries/I2S/I2S.cpp
  libraries/I2S/I2S.h
  libraries/I2S/config.c
  libraries/I2S/examples/RecordAndStream/RecordAndStream.ino
  variants/PORTENTA_C33/pins_arduino.h
Labels: type: enhancement, topic: code

#287 define digitalPinHasPWM for UNOWIFIR4 & MINIMA
  variants/MINIMA/pins_arduino.h
  variants/UNOWIFIR4/pins_arduino.h
Labels: type: enhancement, topic: code
