Repository arduino/ArduinoCore-renesas, pull requests merged in 2024-03, with the labels that each got.

#279 Add hourglass animation to the LED matrix gallery
  libraries/Arduino_LED_Matrix/src/gallery.h
Labels: type: enhancement, topic: code

#258 backtrace: remove spurious file from compiling
  cores/arduino/cm_backtrace/fault_handler/gcc/cmb_fault.S
Labels: type: imperfection, topic: code

#209 CNetIf - added config method to apply new static IP settings for WiFi and Ethernet
  libraries/Ethernet/src/Ethernet.cpp
  libraries/WiFi/src/WiFi.cpp
  libraries/lwIpWrapper/src/CNetIf.cpp
  libraries/lwIpWrapper/src/CNetIf.h
Labels: topic: code

#199 WiFiC3 - config(ip) didn't set default value for DNS IP
  libraries/WiFi/src/WiFi.cpp
Labels: type: imperfection, topic: code
