Repository arduino/ArduinoCore-renesas, pull requests merged in 2024-02, with the labels that each got.

#255 WiFiSSLClient: remove unused function declaration
  libraries/WiFiS3/src/WiFiSSLClient.h
Labels: type: imperfection, topic: code

#252 Docs: UNO R4 WiFi fix command to flash bootloader
  bootloaders/UNO_R4/README.md
Labels: type: imperfection, topic: documentation

#239 Add WiFi Preferences support
  .github/workflows/compile-examples.yml
  libraries/Preferences/examples/Prefs2Struct/Prefs2Struct.ino
  libraries/Preferences/examples/StartCounter/StartCounter.ino
  libraries/Preferences/keywords.txt
  libraries/Preferences/library.properties
  libraries/Preferences/src/Preferences.cpp
  libraries/Preferences/src/Preferences.h
Labels: type: enhancement, topic: code

#253 Add software AT secure element support
  .github/workflows/compile-examples.yml
  libraries/SoftwareATSE/.unor4_only
  libraries/SoftwareATSE/examples/SATSECertificate/SATSECertificate.ino
  libraries/SoftwareATSE/examples/SATSEPrivateKey/SATSEPrivateKey.ino
  libraries/SoftwareATSE/examples/SATSERandomNumber/SATSERandomNumber.ino
  libraries/SoftwareATSE/examples/SATSESerialNumber/SATSESerialNumber.ino
  libraries/SoftwareATSE/examples/SATSESignAndVerify/SATSESignAndVerify.ino
  libraries/SoftwareATSE/library.properties
  libraries/SoftwareATSE/src/SoftwareATSE.cpp
  libraries/SoftwareATSE/src/SoftwareATSE.h
Labels: type: enhancement, topic: code

#144 WiFiS3 WiFiServer::accept()
  libraries/WiFiS3/examples/WiFiAdvancedChatServer/WiFiAdvancedChatServer.ino
  libraries/WiFiS3/examples/WiFiAdvancedChatServer/arduino_secrets.h
  libraries/WiFiS3/src/WiFiServer.cpp
  libraries/WiFiS3/src/WiFiServer.h
Labels: type: enhancement, topic: code

#148 WiFiS3 client connect timeout
  libraries/WiFiS3/src/WiFiClient.cpp
  libraries/WiFiS3/src/WiFiClient.h
  libraries/WiFiS3/src/WiFiSSLClient.cpp
Labels: type: enhancement, topic: code

#197 OTAUpdate: do not use Error enum to return error codes
  libraries/OTAUpdate/examples/OTA/OTA.ino
  libraries/OTAUpdate/examples/WiFiFirmwareOTA/WiFiFirmwareOTA.ino
  libraries/OTAUpdate/src/OTAUpdate.cpp
  libraries/OTAUpdate/src/OTAUpdate.h
Labels: type: enhancement, topic: code

#242 Add AES encrypt/decrypt and HMAC support for SE05X
  libraries/SE05X/examples/SE05XAESEncryptandDecrypt/SE05XAESEncryptandDecrypt.ino
  libraries/SE05X/examples/SE05XAESWriteKey/SE05XAESWriteKey.ino
  libraries/SE05X/examples/SE05XHMAC/SE05XHMAC.ino
  libraries/SE05X/src/SE05X.cpp
  libraries/SE05X/src/SE05X.h
  libraries/SE05X/src/lib/apdu/se05x_APDU_apis.h
  libraries/SE05X/src/lib/apdu/se05x_APDU_impl.c
  libraries/SE05X/src/lib/apdu/se05x_types.h
Labels: type: enhancement, topic: code

#260 Fix: do not randomly clear the first line of the LED matrix.
  libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h
Labels: type: imperfection, topic: code

#254 WiFiSSLClient: add setEccSlot method to configure client private key and certificate
  libraries/WiFiS3/src/WiFiSSLClient.cpp
  libraries/WiFiS3/src/WiFiSSLClient.h
Labels: type: enhancement, topic: code

#248 ESPHost - fix softAP password check
  libraries/ESPhost/src/CCtrlWrapper.h
Labels: type: imperfection, topic: code

#224 WiFiS3 let WiFi.h include WiFiClient, WiFiUDP, WiFiServer
  libraries/WiFiS3/src/WiFi.h
  libraries/WiFiS3/src/WiFiS3.h
Labels: topic: code
