Repository arduino/ArduinoCore-renesas, pull requests merged in 2024-10, with the labels that each got.

#365 Exclude OPTA_* from unor4 package
  variants/OPTA_ANALOG/.portenta_only
  variants/OPTA_DIGITAL/.portenta_only
Labels: type: imperfection, topic: infrastructure

#374 Fix stop bit time.
  libraries/SoftwareSerial/src/SoftwareSerial.cpp
Labels: type: imperfection, topic: code

#370 Core renesas / Storage library, Fix for #366 (Name conflict in library Storage)
  libraries/BlockDevices/CodeFlashBlockDevice.cpp
  libraries/BlockDevices/MBRBlockDevice.cpp
  libraries/BlockDevices/QSPIFlashBlockDevice.cpp
  libraries/FATFilesystem/FATFileSystem.cpp
  libraries/Storage/storage_common.cpp
  libraries/Storage/storage_common.h
Labels: topic: code

#378 package: remove opta variants from boards.txt before packaging
  extras/package.sh
Labels: type: imperfection, topic: infrastructure
