Repository arduino/ArduinoCore-renesas, pull requests merged in 2024-11, with the labels that each got.

#386 UNO R4 WiFi: SATSE add serialNumber(byte sn[]) API
  libraries/SoftwareATSE/src/SoftwareATSE.cpp
  libraries/SoftwareATSE/src/SoftwareATSE.h
Labels: type: enhancement, topic: code

#385 Portenta C33 WiFi: get STA MAC address as default
  libraries/WiFi/src/WiFi.cpp
Labels: type: enhancement, topic: code

#384 WiFiS3: add WL_MAC_ADDR_LENGTH definition
  libraries/WiFiS3/src/WiFi.cpp
  libraries/WiFiS3/src/WiFi.h
Labels: type: enhancement, topic: code

#383 SE050 add api to read serial number bytes
  libraries/SE05X/src/SE05X.cpp
  libraries/SE05X/src/SE05X.h
Labels: type: imperfection, topic: code

#392 Add `SERIAL_PORT_HARDWARE`
  variants/PORTENTA_C33/pins_arduino.h
Labels: type: imperfection, topic: code

#394 WiFiS3: add WiFi.getTime()
  libraries/WiFiS3/examples/WiFiTime/WiFiTime.ino
  libraries/WiFiS3/examples/WiFiTime/arduino_secrets.h
  libraries/WiFiS3/src/WiFi.cpp
Labels: type: imperfection, topic: code

#395 Add WiFi.ping()
  libraries/WiFiS3/examples/WiFiPing/WiFiPing.ino
  libraries/WiFiS3/examples/WiFiPing/arduino_secrets.h
  libraries/WiFiS3/src/WiFi.cpp
  libraries/WiFiS3/src/WiFi.h
  libraries/WiFiS3/src/WiFiTypes.h
Labels: type: enhancement, topic: code

#326 WifiS3 added method to get uint32 version
  libraries/WiFiS3/src/Modem.cpp
  libraries/WiFiS3/src/WiFi.cpp
  libraries/WiFiS3/src/WiFi.h
Labels: type: enhancement, topic: code

#393 Preferences fixes
  libraries/Preferences/examples/TypesCheck/TypesCheck.ino
  libraries/Preferences/src/Preferences.cpp
Labels: type: imperfection, topic: code

#369 Arduino_FreeRTOS: automatically start loop
  cores/arduino/main.cpp
  libraries/Arduino_FreeRTOS/src/portable/FSP/port.c
Labels: topic: code

#325 Non blocking ota download
  libraries/OTAUpdate/examples/OTANonBlocking/OTANonBlocking.ino
  libraries/OTAUpdate/examples/OTANonBlocking/arduino_secrets.h
  libraries/OTAUpdate/examples/OTANonBlocking/root_ca.h
  libraries/OTAUpdate/src/OTAUpdate.cpp
  libraries/OTAUpdate/src/OTAUpdate.h
Labels: type: enhancement, topic: code

#401 TextWithArduinoGraphics: add note about ArduinoGraphics dependency
  libraries/Arduino_LED_Matrix/examples/TextWithArduinoGraphics/TextWithArduinoGraphics.ino
  libraries/Arduino_LED_Matrix/examples/TextWithArduinoGraphicsAsynchronous/TextWithArduinoGraphicsAsynchronous.ino
Labels: type: imperfection, topic: documentation

#403 WiFiS3 ping add missing parameter
  libraries/WiFiS3/src/WiFi.cpp
Labels: type: imperfection, topic: code

#402 examples: uno r4 wifi fix print about required firmware version
  libraries/Preferences/examples/TypesCheck/TypesCheck.ino
  libraries/WiFiS3/examples/WiFiPing/WiFiPing.ino
  libraries/WiFiS3/examples/WiFiTime/WiFiTime.ino
Labels: type: imperfection, topic: documentation

#405 Fix for Serial flush() returning before transmission has completed
  cores/arduino/Serial.cpp
  cores/arduino/Serial.h
Labels: type: imperfection, topic: code
