Repository arduino/ArduinoCore-renesas, pull requests merged in 2024-01, with the labels that each got.

#227 ESPHost library - make the example work
  libraries/ESPhost/examples/ESP32_TEST/ESP32_TEST.ino
  libraries/ESPhost/src/CEspControl.h
Labels: type: imperfection, topic: documentation

#231 Prevent multiple inclusion by adding include guards.
  libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h
Labels: type: enhancement, topic: code

#232 Fix: prevent artefacts from appearing on the screen during a SCROLL_LEFT.
  libraries/Arduino_LED_Matrix/examples/TextWithArduinoGraphics/TextWithArduinoGraphics.ino
  libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h
Labels: type: enhancement, topic: code

#222 Ethernet.begin - fix parameters ordering
  libraries/Ethernet/src/Ethernet.cpp
  libraries/Ethernet/src/EthernetC33.h
Labels: type: imperfection, topic: code

#223 EthernetC33 debugging
  libraries/Ethernet/src/Ethernet.cpp
  libraries/lwIpWrapper/src/CNetIf.cpp
  libraries/lwIpWrapper/src/CNetIf.h
Labels: topic: code

#229 Fixed hash algo to be selected based on input and not hardcoded
  extras/tls/mbedtls_alt/ecdsa_se05x.c
  libraries/SSLClient/src/cortex-m33/libmbedse05x.a
Labels: type: enhancement, topic: code

#147 WiFiS3 fix Modem timeout at ERROR response
  libraries/WiFiS3/src/Modem.cpp
Labels: type: imperfection, topic: code

#217 Fixed encoding of KeySlot ID.
  libraries/SSLClient/src/SSLClient.cpp
Labels: type: imperfection, topic: code

#238 Define the `compiler.optimization_flags` allows for specifying the desired optimization level during compilation.
  platform.txt
Labels: type: enhancement, topic: code

#245 Fix typo
  libraries/WiFiS3/examples/WiFiWebClientSSL/WiFiWebClientSSL.ino
Labels: type: imperfection, topic: documentation

#246 - fix for #244, byte-order wrong for LSBFIRST buffer transfers
  libraries/SPI/SPI.cpp
Labels: type: imperfection, topic: code
