Repository arduino/ArduinoCore-renesas, pull requests merged in 2025-03, with the labels that each got.

#424 Ping command for Portenta C33
  extras/net/lwipopts.h
  libraries/Ethernet/examples/EthernetPing/EthernetPing.ino
  libraries/Ethernet/src/Ethernet.cpp
  libraries/Ethernet/src/EthernetC33.h
  libraries/WiFi/examples/WiFiPing/WiFiPing.ino
  libraries/WiFi/examples/WiFiPing/arduino_secrets.h
  libraries/WiFi/src/WiFi.cpp
  libraries/WiFi/src/WiFiC3.h
  libraries/lwIpWrapper/src/CNetIf.cpp
  libraries/lwIpWrapper/src/CNetIf.h
  libraries/lwIpWrapper/src/cortex-m33/liblwIP.a
  libraries/lwIpWrapper/src/lwipopts.h
Labels: type: enhancement, topic: code

#387 Add limit for returning the first 10 access points with high rssi
  libraries/WiFiS3/src/WiFi.cpp
  libraries/WiFiS3/src/WiFi.h
Labels: type: imperfection, topic: code

#415 Adding WiFiS3 API documentation
  .gitignore
  libraries/WiFiS3/docs/api.md
  libraries/WiFiS3/src/Modem.h
  libraries/WiFiS3/src/StringHelpers.h
  libraries/WiFiS3/src/WiFi.h
  libraries/WiFiS3/src/WiFiClient.h
  libraries/WiFiS3/src/WiFiFileSystem.h
  libraries/WiFiS3/src/WiFiSSLClient.h
  libraries/WiFiS3/src/WiFiServer.h
  libraries/WiFiS3/src/WiFiUdp.h
Labels: topic: documentation, type: enhancement
