Repository arduino/ArduinoCore-renesas, pull requests merged in 2025-02, with the labels that each got.

#427 UNO R4 WiFi Fix firmware init from cold boot
  libraries/WiFiS3/src/Modem.cpp
  libraries/WiFiS3/src/Modem.h
Labels: type: imperfection, topic: code

#429 Upgrade upload/artifacts and checkout actions to v4
  .github/workflows/compile-examples.yml
Labels: type: imperfection, topic: infrastructure

#423 WiFiS3: fix peek() avoiding AT call
  libraries/WiFiS3/src/WiFiClient.cpp
Labels: type: imperfection, topic: code

#432 WiFiS3: remove destroy_at_distructor unused flag
  libraries/WiFiS3/src/WiFiClient.cpp
  libraries/WiFiS3/src/WiFiClient.h
Labels: topic: code

#435 analog: declare aref variable only if used
  cores/arduino/analog.cpp
Labels: topic: code

#439 WiFiS3 and WiFIC3 Add wl definitions
  libraries/WiFiS3/src/WiFi.h
  libraries/WiFiS3/src/WiFiTypes.h
  libraries/lwIpWrapper/src/CNetIf.cpp
  libraries/lwIpWrapper/src/CNetIf.h
Labels: type: enhancement, topic: code

#443 Esphost add missing return values and minor fixes
  libraries/ESPhost/src/CMsg.cpp
  libraries/ESPhost/src/EspSpiDriver.cpp
Labels: type: imperfection, topic: code

#440 C33 Ethernet fix warnings
  libraries/Ethernet/src/Ethernet.cpp
  libraries/Ethernet/src/EthernetClock.cpp
  libraries/Ethernet/src/EthernetDriver.cpp
Labels: type: imperfection, topic: code

#441 lwIpWrapper: fix redefinitions, ctor init order and remove unused variables
  libraries/lwIpWrapper/src/CNetIf.cpp
  libraries/lwIpWrapper/src/CNetIf.h
  libraries/lwIpWrapper/src/lwipClient.cpp
  libraries/lwIpWrapper/src/lwipDhcpServer.c
Labels: type: imperfection, topic: code

#436 C33 SSL client fix stop() and connect( .. ) with psk
  libraries/SSLClient/src/SSLClient.cpp
  libraries/SSLClient/src/ssl_client.cpp
  libraries/SSLClient/src/ssl_client.h
  libraries/SSLClient/src/ssl_debug.cpp
  libraries/SSLClient/src/ssl_debug.h
Labels: type: imperfection, topic: code

#444 BlockDevices: minor fixes to cleanup compile warnings
  libraries/BlockDevices/QSPIFlashBlockDevice.cpp
  libraries/BlockDevices/QSPIFlashBlockDevice.h
  libraries/BlockDevices/SDCardBlockDevice.cpp
  libraries/BlockDevices/SDCardBlockDevice.h
  libraries/Storage/storage_common.h
Labels: type: imperfection, topic: code

#445 FreeRTOS restore original behaviour and allow override startup hooks
  boards.txt
  cores/arduino/main.cpp
  libraries/Arduino_FreeRTOS/src/Arduino_FreeRTOS.h
  libraries/Arduino_FreeRTOS/src/portable/FSP/port.c
Labels: type: enhancement, topic: code

#428 [C33] Kvstore
  .github/workflows/compile-examples.yml
  libraries/KVStore/.portenta_only
  libraries/KVStore/examples/StartCounter/StartCounter.ino
  libraries/KVStore/library.properties
  libraries/KVStore/src/KVStore.h
  libraries/KVStore/src/MbedCRC.h
  libraries/KVStore/src/TDBStore.cpp
  libraries/KVStore/src/TDBStore.h
  libraries/Storage/examples/QSPIFormat/QSPIFormat.ino
Labels: type: enhancement, topic: code

#437 RTC: add structs missing initializers
  libraries/RTC/src/RTC.cpp
Labels: type: imperfection, topic: code
