Repository arduino/ArduinoCore-renesas, pull requests merged in 2025-06, with the labels that each got.

#470 Storage: align partition scheme to mbed boards
  libraries/Storage/examples/QSPIFormat/QSPIFormat.ino
  libraries/Storage/examples/QSPIFormat/certificates.h
Labels: topic: documentation, type: enhancement, topic: code

#468 Matrix: initialize _lastInterval when starting a sequence
  libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h
Labels: type: imperfection, topic: code

#467 Reduce storage consumption of ping command for C33
  libraries/lwIpWrapper/src/CNetIf.cpp
Labels: type: enhancement, topic: code

#474 Replace broken URLs in library metadata
  libraries/SDU/library.properties
  libraries/SFU/library.properties
  libraries/WiFiS3/library.properties
  libraries/lwIpWrapper/library.properties
Labels: type: imperfection
